In [10]:
# Data Preprocessing Template

# Importing the libraries
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
np.set_printoptions(suppress=True) # supress scientific number

In [11]:
# Importing the dataset
dataset = pd.read_csv('Data.csv')
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, 3].values

dataset,X,y

(   Country   Age   Salary Purchased
 0   France  44.0  72000.0        No
 1    Spain  27.0  48000.0       Yes
 2  Germany  30.0  54000.0        No
 3    Spain  38.0  61000.0        No
 4  Germany  40.0      NaN       Yes
 5   France  35.0  58000.0       Yes
 6    Spain   NaN  52000.0        No
 7   France  48.0  79000.0       Yes
 8  Germany  50.0  83000.0        No
 9   France  37.0  67000.0       Yes, array([['France', 44.0, 72000.0],
        ['Spain', 27.0, 48000.0],
        ['Germany', 30.0, 54000.0],
        ['Spain', 38.0, 61000.0],
        ['Germany', 40.0, nan],
        ['France', 35.0, 58000.0],
        ['Spain', nan, 52000.0],
        ['France', 48.0, 79000.0],
        ['Germany', 50.0, 83000.0],
        ['France', 37.0, 67000.0]], dtype=object), array(['No', 'Yes', 'No', 'No', 'Yes', 'Yes', 'No', 'Yes', 'No', 'Yes'],
       dtype=object))

In [12]:
# Splitting the dataset into the Training set and Test set
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

X_train, y_train

(array([['Germany', 40.0, nan],
        ['France', 37.0, 67000.0],
        ['Spain', 27.0, 48000.0],
        ['Spain', nan, 52000.0],
        ['France', 48.0, 79000.0],
        ['Spain', 38.0, 61000.0],
        ['France', 44.0, 72000.0],
        ['France', 35.0, 58000.0]], dtype=object),
 array(['Yes', 'Yes', 'Yes', 'No', 'Yes', 'No', 'No', 'Yes'], dtype=object))

In [13]:
# Taking care of missing data
from sklearn.preprocessing import Imputer
imputer = Imputer(missing_values = 'NaN', strategy = 'mean', axis = 0)
imputer = imputer.fit(X[:, 1:3])
X[:, 1:3] = imputer.transform(X[:, 1:3])

# Encoding categorical data
# Encoding the Independent Variable
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
labelencoder_X = LabelEncoder()
X[:, 0] = labelencoder_X.fit_transform(X[:, 0])
onehotencoder = OneHotEncoder(categorical_features = [0])
X = onehotencoder.fit_transform(X).toarray()
# Encoding the Dependent Variable
labelencoder_y = LabelEncoder()
y = labelencoder_y.fit_transform(y)

X, y

(array([[    1.        ,     0.        ,     0.        ,    44.        ,
         72000.        ],
        [    0.        ,     0.        ,     1.        ,    27.        ,
         48000.        ],
        [    0.        ,     1.        ,     0.        ,    30.        ,
         54000.        ],
        [    0.        ,     0.        ,     1.        ,    38.        ,
         61000.        ],
        [    0.        ,     1.        ,     0.        ,    40.        ,
         63777.77777778],
        [    1.        ,     0.        ,     0.        ,    35.        ,
         58000.        ],
        [    0.        ,     0.        ,     1.        ,    38.77777778,
         52000.        ],
        [    1.        ,     0.        ,     0.        ,    48.        ,
         79000.        ],
        [    0.        ,     1.        ,     0.        ,    50.        ,
         83000.        ],
        [    1.        ,     0.        ,     0.        ,    37.        ,
         67000.        ]]), array([0

In [14]:
# Taking care of missing data
from sklearn.preprocessing import Imputer
X = dataset.iloc[:, 1:3].values
y = dataset.iloc[:, 3].values
imputer = Imputer(missing_values = 'NaN', strategy = 'mean', axis = 0)
imputer = imputer.fit(X)
X = imputer.transform(X)

X

array([[   44.        , 72000.        ],
       [   27.        , 48000.        ],
       [   30.        , 54000.        ],
       [   38.        , 61000.        ],
       [   40.        , 63777.77777778],
       [   35.        , 58000.        ],
       [   38.77777778, 52000.        ],
       [   48.        , 79000.        ],
       [   50.        , 83000.        ],
       [   37.        , 67000.        ]])

In [15]:
# Feature Scaling
from sklearn.preprocessing import StandardScaler

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

sc_X = StandardScaler()
X_train = sc_X.fit_transform(X_train)
X_test = sc_X.transform(X_test)

X_train, X_test

(array([[ 0.26306757,  0.12381479],
        [-0.25350148,  0.46175632],
        [-1.97539832, -1.53093341],
        [ 0.05261351, -1.11141978],
        [ 1.64058505,  1.7202972 ],
        [-0.0813118 , -0.16751412],
        [ 0.95182631,  0.98614835],
        [-0.59788085, -0.48214934]]), array([[-1.45882927, -0.90166297],
        [ 1.98496442,  2.13981082]]))